# FILE LOCATION IN REPOSITORY:
#
#   .github/workflows/auto-build-on-base-image-change.yml
#

name: Regular base image update check
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
  
env:
  IMAGE_TAG: stnokott/nextcloud-custom:latest


jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: nextcloud:stable-apache
          image: ${{ env.IMAGE_TAG }} # update for your image

      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: .
          tags: ${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64,linux/armv7,linux/armv8
          cache-from: type=registry,ref=${{ env.IMAGE_TAG }}
          cache-to: type=inline
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
